apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - nginx-deployment.yaml
  - nginx-service.yaml
  - prometheus-deployment.yaml
  - prometheus-service.yaml
  - prometheus-configmap.yaml
  - prometheus-sa.yaml
  - nginx-configmap.yaml
#configMapGenerator:
#  - name: prometheus-config
#    files:
#      - prometheus.yml