apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: nginx-deployment
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'nginx'
        static_configs:
          - targets: ['nginx-exporter-service.nginx-deployment.svc.cluster.local:9113']
