global:
  scrape_interval: 15s 

scrape_configs:
  - job_name: 'nginx'
    static_configs:
      #- targets: ['nginx-service.nginx:9113']
      - targets: ['nginx-service.nginx.svc.cluster.local:9113']
