apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment
  namespace: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:v3.1.0
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: config-volume
          mountPath: /etc/prometheus/
          readOnly: true

      - name: debug
        image: curlimages/curl:latest
        command: ["sleep"]
        args: ["infinity"]

      volumes:
      - name: config-volume
        configMap:
          name: prometheus-config
